
version : '3.8'

services:
  app:
    image: rating-system
    container_name: ratingSystem-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_REDIS_HOST=redis
      - GMAIL_ADDRESS=${EMAIL}
      - GMAIL_PASSWORD=${PASSWORD}
    depends_on:
      -postgres
      -redis
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USE: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"